# Generated by Django 3.1.5 on 2022-01-22 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('session_id', models.TextField(blank=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('realm', models.CharField(default='', max_length=200)),
                ('challenge', models.CharField(default='', max_length=200)),
                ('achievements', models.CharField(default='', max_length=200)),
                ('joined', models.CharField(default='', max_length=200)),
                ('poe_account', models.JSONField(default=dict, null=True)),
                ('last_character', models.JSONField(default=dict, null=True)),
                ('karma', models.IntegerField(default=0)),
                ('positive_karma', models.IntegerField(default=0)),
                ('unique_positive', models.IntegerField(default=0)),
                ('negative_karma', models.IntegerField(default=0)),
                ('unique_negative', models.IntegerField(default=0)),
                ('is_opened', models.BooleanField(default=False)),
                ('is_stream_ready', models.BooleanField(default=False)),
                ('is_collateral_ready', models.BooleanField(default=False)),
                ('max_collateral_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.JSONField(default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
