# Generated by Django 3.1.5 on 2022-01-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220127_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='characters',
            field=models.JSONField(default=list, null=True),
        ),
    ]
