# Generated by Django 3.1.5 on 2022-01-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poe_token',
            field=models.JSONField(default=dict),
        ),
    ]
