# Generated by Django 3.1.5 on 2022-01-22 04:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': None,
            },
        ),
        migrations.CreateModel(
            name='TradingHallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': None,
            },
        ),
        migrations.CreateModel(
            name='TradingHallService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=1000)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tags', models.JSONField(default=list)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.tradinghallcategory')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_level', models.IntegerField(db_index=True, default=0)),
                ('price', models.CharField(db_index=True, max_length=200)),
                ('float_price', models.FloatField(db_index=True, default=0)),
                ('user_credit', models.IntegerField(db_index=True, default=0)),
                ('chaos_equivalent', models.FloatField(default=0)),
                ('ex_equivalent', models.FloatField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('options', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.league')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.tradinghallservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('chaos_equivalent',),
                'unique_together': {('user', 'league', 'service')},
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('chaos_equivalent', models.FloatField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.league')),
            ],
            options={
                'ordering': None,
            },
        ),
        migrations.CreateModel(
            name='UserVouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('karma', models.IntegerField(db_index=True, default=0)),
                ('note', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.userservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('user', 'service')},
            },
        ),
        migrations.CreateModel(
            name='TradingHallPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('average', models.FloatField(default=0)),
                ('median', models.FloatField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.league')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poe.tradinghallservice')),
            ],
            options={
                'ordering': None,
                'unique_together': {('service', 'league')},
            },
        ),
    ]
