# Generated by Django 3.1.5 on 2022-01-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poe', '0004_auto_20220127_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradinghallcategory',
            options={'ordering': ('-priority',)},
        ),
        migrations.AddField(
            model_name='tradinghallservice',
            name='options',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='tradinghallservice',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
